stages:
  model_training:
    cmd: python starter/starter/train_model.py
    deps:
    - starter/data/census_clean.csv
    - starter/starter/train_model.py
    outs:
    - starter/model/encoder.pkl
    - starter/model/lb.pkl
    - starter/model/model.pkl
  performance_slices:
    cmd: python starter/starter/performance_slices.py
    deps:
    - starter/data/census_clean.csv
    - starter/model/encoder.pkl
    - starter/model/lb.pkl
    - starter/model/model.pkl
    - starter/starter/performance_slices.py
    outs:
    - starter/starter/slice_output.txt
